Feat: Add Service Stacking
debionetwork/debio-node pull request #45
Opened 2021-08-02 05:54 UTC by SHA888

### JIRA Link
https://blocksphere2020.atlassian.net/browse/DBIO-377?atlOrigin=eyJpIjoiNzJkMGRiMmIwOTMyNDU2OTk0NGI4YmIwNTFiNmUzMzMiLCJwIjoiaiJ9

### Changelog / Description
Substrate request service staking (staking event)
- Add fn request_service_staking
- Add dai_hash params
- Add DaiHash type
- Add  ServiceStacked event
- Add ServiceStakingIsRequired error

2021-08-04 01:35 UTC, kevinjanada commented on pallets/services/src/interface.rs
> +    type DaiHash;
Krn ini kan sbnar nya transaction hash, gmn kalo namanya txHash aja?

2021-08-04 01:36 UTC, kevinjanada commented on pallets/services/src/lib.rs
> +        ServiceStacked(ServiceOf<T>, AccountIdOf<T>),
Typo yak bli, hrsnya ServiceStaked

2021-08-04 01:49 UTC, SHA888 commented on pallets/services/src/interface.rs
> +    type DaiHash;
Ok siap mas

2021-08-04 01:49 UTC, SHA888 commented on pallets/services/src/lib.rs
> +        ServiceStacked(ServiceOf<T>, AccountIdOf<T>),
Oh iya typo, thank you mas.

2021-08-04 01:51 UTC, kevinjanada requested changes
Aku review ya bli

2021-08-04 01:51 UTC, kevinjanada commented on pallets/services/src/lib.rs
> +    }
Bli, untuk function ini,
Kmungkinan customer bisa melakukan request service pada lab yg sudah ada, ataupun lab yang belum ada.
Jadi parameternya perlu lab_id: Option<&T::AccountId>

Lalu, karena. request service ini sbnarnya adalah request service yg belum ada, kita ga bisa masukin ServiceId di sini sih, mau ga mau harus string Vec<u8>

Trus, mnurutku kita bisa masukin staking_amount: Balance / u128 di dalem sini sih, biar gampang ngambil amount nya

Lalu, kita perlu buat storage lagi untuk menyimpan request ini
Kalau skarang aku lihat, yg di line 364, tidak perlu, krn ini cuma re insert service saja

Kalau aku suggest, bikin struct
```rust
struct ServiceRequest {
    lab_id: Option<AccountId>, 
    service_category: Vec<u8>,
    amount_staked: u128,
    tx_hash: Hash,
}
```

2021-08-04 02:11 UTC, SHA888 commented on pallets/services/src/lib.rs
> +    }
Wah terima kasih atas pencerahannya mas. Lebih kebayang sekarang :)

2021-08-12 01:17 UTC, kevinjanada requested changes
Reviewed

2021-08-12 01:17 UTC, kevinjanada commented on pallets/services/src/interface.rs
> +    fn request_service_staking(owner_id: &T::AccountId, lab_id: Option<&T::AccountId>, service_category: Vec<u8>, amount_staked: u128, tx_hash: &Self::TxHash, country: Vec<u8>, city: Vec<u8>) -> Resu
Bli, setelah aku review lagi flow nya, kita butuh 1 parameter lagi yaitu request_hash. nanti request_hash ini digunakan untuk ngambil data request nya di smart contract. Minta tolong ditambah ya

2021-08-12 01:17 UTC, kevinjanada commented on pallets/services/src/lib.rs
> +    fn request_service_staking(owner_id: &T::AccountId, lab_id: Option<&T::AccountId>, service_category: Vec<u8>, amount_staked: u128, tx_hash: &Self::TxHash, country: Vec<u8>, city: Vec<u8>) -> Resu
Untuk function ini bli, tujuan nya adalah untuk menyimpan data request di blockchain kita.
Jadi kita perlu menambah satu buah storage untuk menyimpan data request.

Untuk sekarang data request ini belum ada hubungan nya dengan data service yg ada di storage sekarang bli.
Jadi tidak perlu get service by tx_hash.

2021-08-12 01:54 UTC, SHA888 commented on pallets/services/src/lib.rs
> +    fn request_service_staking(owner_id: &T::AccountId, lab_id: Option<&T::AccountId>, service_category: Vec<u8>, amount_staked: u128, tx_hash: &Self::TxHash, country: Vec<u8>, city: Vec<u8>) -> Resu
Ok mas. Sipp

2021-08-12 04:36 UTC, kevinjanada commented on pallets/services/src/lib.rs
> +    fn request_service_staking(owner_id: &T::AccountId, lab_id: Option<&T::AccountId>, service_category: Vec<u8>, amount_staked: u128, tx_hash: &Self::TxHash, country: Vec<u8>, city: Vec<u8>) -> Resu
Bli, ada tambahan. Data ServiceRequest nya perlu bbrapa tambahan field. jadi nya sperti ini
```rust
  enum ServiceRequestStatus {
      Open,
      InProgress,
      Fulfilled,
  }
  impl Default for ServiceRequestStatus {
       fn default() -> Self { ServiceRequestStatus::Open }   
  }
  struct ServiceRequest {
      owner_id: AccountId,
      lab_id: Option<AccountId>, 
      service_category: Vec<u8>,
      amount_staked: u128,
      tx_hash: Hash,
      request_hash: Hash,
      status: ServiceRequestStatus
  }
```

2021-08-12 05:44 UTC, SHA888 commented on pallets/services/src/lib.rs
> +    fn request_service_staking(owner_id: &T::AccountId, lab_id: Option<&T::AccountId>, service_category: Vec<u8>, amount_staked: u128, tx_hash: &Self::TxHash, country: Vec<u8>, city: Vec<u8>) -> Resu
Noted mas

2021-08-20 09:10 UTC, closed without merging