Feat: Substrate update people who stake + notification
debionetwork/debio-node pull request #54
Opened 2021-08-20 05:29 UTC by SHA888

## JIRA link
https://blocksphere2020.atlassian.net/browse/DBIO-545?atlOrigin=eyJpIjoiYmVlMTdhMjlkMjEyNDBiMGE3ZGM2N2M5ZjZkMjJjZjYiLCJwIjoiaiJ9

## Changelog / Description
Update substrate on list of people who stake + notification

- Add Stakers trait in user-profile pallet
- Add `stakers by account id getter` and `setter` fn in user-profile pallet
- Add `StakersByAccountId` storage in user-profile pallet

2021-08-20 09:38 UTC, kevinjanada requested changes
Please refer to JIRA Card

2021-08-20 13:16 UTC, SHA888 commented
Noted mas. Thank you

2021-08-31 11:25 UTC, kevinjanada requested changes

2021-08-31 11:25 UTC, kevinjanada commented on pallets/genetic-testing/src/lib.rs
> +        DataStaked(HashOf<T>)
di dalem DataStaked minta tolong ditambah AccountId si staker nya yah bli

2021-08-31 11:25 UTC, kevinjanada commented on pallets/genetic-testing/src/lib.rs
> +        }
Bli @SHA888 , kliatannya ini gak perlu bli, dia hanya membandingkan dengan variable itu sendiri.
Dan untuk nge submit ini memang harusnya gak perlu ada validasi

2021-08-31 13:24 UTC, SHA888 commented
Mas @kevinjanada sudah aku perbaikin ya mas. Tolong dicek kembali. Thank you

2021-08-31 13:37 UTC, kevinjanada approved these changes
Looks good

2021-08-31 13:37 UTC, merged